on:
  schedule:
    # https://crontab.guru/#0_8-22/2_*_*_*
    # At minute 0 past every hour from 8 through 22.
    - cron: "0 8-22/2 * * *"
jobs:
  build:
    name: Backup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Import Data
        run: yarn cms
      - name: Git Push
        run: |
          git config user.name cmsonfire
          git add .
          git commit -m "generated"
          git push
