name: Backup Data
on:
  schedule:
    - cron: "*/10 8-20 * * *"
    # https://crontab.guru/#0_8-22/2_*_*_*
    # At minute 0 past every 2nd hour from 8 through 22. '0 8-22/2 * * *'
jobs:
  build:
    name: Backup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Import Data
        run: npm run-script cms
        env:
          GOOGLE_APPLICATION_ADMIN: ${{ secrets.GOOGLE_APPLICATION_ADMIN }}
      - name: Git Push
        run: |
          git config user.name cmsonfire
          git add .
          git commit -m "generated"
          git push
