name: Backup Data
on:
  schedule:
    - cron: "0 0-23/6 * * *"
    # https://crontab.guru/#0_0-23/6_*_*_*
    # At minute 0 past every 6th hour from 0 through 23. '0 0-23/6 * * *'
jobs:
  import:
    name: Backup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Import Data
        run: npm run-script cms
        env:
          GOOGLE_APPLICATION_ADMIN: ${{ secrets.GOOGLE_APPLICATION_ADMIN }}
      - name: Git Push
        run: |
          git config user.name cmsonfire
          git add .
          git commit -m "generated"
          git push
