name: Test Scheduler
on:
  schedule:
  - cron: '30 * * * *'

jobs:
  go:
    name: Test Cron
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        run: echo "Running every 1 hour on 30 min mark"
